# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Maypole-Plugin-Relationship
version:      0.03
version_from: Relationship.pm
installdirs:  site
requires:
    Class::DBI::Loader::Relationship: 0
    Maypole:                       2.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
